// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALUWTu9fx5Bx6trTKS3GcXPkXYrTht-2U',
    appId: '1:247737032867:web:25926f6c71a36062021f16',
    messagingSenderId: '247737032867',
    projectId: 'tesis-app-log',
    authDomain: 'tesis-app-log.firebaseapp.com',
    storageBucket: 'tesis-app-log.firebasestorage.app',
    measurementId: 'G-P0ZYK9PPP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6lBPujz8yoIsU3noDrYpt2waxbkFAyUY',
    appId: '1:247737032867:android:a55ceb9c248a0e33021f16',
    messagingSenderId: '247737032867',
    projectId: 'tesis-app-log',
    storageBucket: 'tesis-app-log.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLr9oa1YLczwzYyKnhbW8oP9yTEx53NUM',
    appId: '1:247737032867:ios:747e36cd746c9a12021f16',
    messagingSenderId: '247737032867',
    projectId: 'tesis-app-log',
    storageBucket: 'tesis-app-log.firebasestorage.app',
    iosBundleId: 'com.example.appLogic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLr9oa1YLczwzYyKnhbW8oP9yTEx53NUM',
    appId: '1:247737032867:ios:747e36cd746c9a12021f16',
    messagingSenderId: '247737032867',
    projectId: 'tesis-app-log',
    storageBucket: 'tesis-app-log.firebasestorage.app',
    iosBundleId: 'com.example.appLogic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALUWTu9fx5Bx6trTKS3GcXPkXYrTht-2U',
    appId: '1:247737032867:web:d7430e917465526f021f16',
    messagingSenderId: '247737032867',
    projectId: 'tesis-app-log',
    authDomain: 'tesis-app-log.firebaseapp.com',
    storageBucket: 'tesis-app-log.firebasestorage.app',
    measurementId: 'G-T1015WKY17',
  );
}
